#!/usr/bin/env node
// Scans public/ and out/ to build a manifest of audio, video, and image assets.
// Writes portal/assets.js as `window.STUDIO_ASSETS = {...}` so the portal
// index.html can render a browsable tree without a server.
//
// Usage: npm run portal
//   (re-run whenever assets change)

import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, extname } from "node:path";

const ROOT = process.cwd();

const walk = (dir, base = dir) => {
  const out = [];
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const e of entries) {
    if (e.name.startsWith(".")) continue;
    const full = join(dir, e.name);
    if (e.isDirectory()) {
      out.push({
        type: "dir",
        name: e.name,
        path: relative(base, full),
        children: walk(full, base),
      });
    } else if (e.isFile()) {
      const st = statSync(full);
      out.push({
        type: "file",
        name: e.name,
        path: relative(base, full),
        size: st.size,
        ext: extname(e.name).slice(1).toLowerCase(),
      });
    }
  }
  out.sort((a, b) => {
    if (a.type !== b.type) return a.type === "dir" ? -1 : 1;
    return a.name.localeCompare(b.name);
  });
  return out;
};

const countFiles = (tree, pred = () => true) => {
  let n = 0;
  for (const node of tree) {
    if (node.type === "file" && pred(node)) n++;
    else if (node.type === "dir") n += countFiles(node.children, pred);
  }
  return n;
};

const audio = walk(join(ROOT, "public/audio"));
const videos = walk(join(ROOT, "out"));
const images = walk(join(ROOT, "public/assets"));

const manifest = {
  generatedAt: new Date().toISOString(),
  audio,
  videos,
  images,
  counts: {
    audio: countFiles(audio, (f) => f.ext === "mp3"),
    videos: countFiles(videos, (f) => f.ext === "mp4"),
    images: countFiles(images),
  },
};

const outPath = join(ROOT, "portal/assets.js");
writeFileSync(
  outPath,
  `// Auto-generated by scripts/generate-portal.mjs — do not edit.\n` +
    `window.STUDIO_ASSETS = ${JSON.stringify(manifest, null, 2)};\n`,
);

console.log(
  `→ portal/assets.js (${manifest.counts.audio} audio, ` +
    `${manifest.counts.videos} videos, ${manifest.counts.images} images)`,
);
